config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :common do
    resources :dashboard, only: :index

    resources :media
    resources :schedules
    resources :devices

    root to: 'dashboard#index'
  end

  namespace :admin do
    resources :dashboard, only: :index

    resources :users, only: :edit do
      post :create, on: :collection
    end

    resources :user_actions do
      get :export, on: :collection
    end
  end

  namespace :api do
    resources :devices, only: [] do
      get :schedule, on: :collection
    end
  end

  root to: redirect('/common')
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController
  defaults resource_class: User

  navigation_section :admin_dashboard
end

app/controllers/common/dashboard_controller.rb
class Common::DashboardController < AuthenticatedController
  defaults resource_class: User

  navigation_section :dashboard
end

app/helpers/common/dashboard_helper.rb
module Common::DashboardHelper
  def dashdoard_greeting
    t('common.dashboard.greetings', email: current_user.email)
  end

  def dashboard_statistics
    t('common.dashboard.devices_stats', devices_amount: Device.count, enabled_devices_amount: Device.enabled.count)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def dashdoard_greeting
    t('common.dashboard.greetings', email: current_user.email)
  end

  def dashboard_statistics
    t('common.dashboard.devices_stats', devices_amount: Device.count, enabled_devices_amount: Device.enabled.count)
  end
end

app/views/admin/dashboard/index.html.slim
.row
  .col-sm-4 = admin_stats_card User
  .col-sm-4 = admin_stats_card Device
  .col-sm-4 = admin_stats_card Media

br

.row
  .col-sm-6
    .card
      h5.card-header = t('admin.dashboard.common_actions')
      .card-body
        = bootstrap_button t('admin.dashboard.user_actions_log'), url: admin_user_actions_path, class: 'btn-block'

  .col-sm-6
    .card
      h5.card-header = t('admin.dashboard.create_device_owner')
      .card-body
        = simple_form_for User.new, url: admin_users_path, method: :post do |f|
          = f.input :email
          = f.input :password
          = bootstrap_button t('shared.create'), type: :submit, class: 'btn-block'

br

.card
  h5.card-header = t('admin.dashboard.users_grid')

  = render 'admin/users/grid'