config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :common do
    resources :dashboard, only: :index

    resources :media
    resources :schedules
    resources :devices

    root to: 'dashboard#index'
  end

  namespace :admin do
    resources :dashboard, only: :index

    resources :users, only: :edit do
      post :create, on: :collection
    end

    resources :user_actions do
      get :export, on: :collection
    end
  end

  namespace :api do
    resources :devices, only: [] do
      get :schedule, on: :collection
    end
  end

  root to: redirect('/common')
end

app/controllers/admin/user_actions_controller.rb
class Admin::UserActionsController < AdminController
  defaults resource_class: UserAction

  def export
    send_data(collection.to_json, filename: "user_actions_#{Time.now.to_i}.json", type: 'application/json')
  end

  def collection
    super.ordered.filtered(params[:filter]).presence || super
  end
end

app/helpers/user_actions_helper.rb
module UserActionsHelper
  USER_ACTIONS_BADGES_CLASSES_MAPPING = {
    UserActionType::CREATE => 'badge-success',
    UserActionType::UPDATE => 'badge-warning',
    UserActionType::DELETE => 'badge-danger'
  }.freeze

  def user_action_change_type_badge_for(user_action)
    badge_class = USER_ACTIONS_BADGES_CLASSES_MAPPING[user_action.change_type]

    content_tag(:span, user_action.change_type.upcase, class: "badge #{badge_class}")
  end

  def user_actions_filters
    filters = UserAction.all.pluck(:changed_object_type).map do |filter|
      param_filter = filter.underscore

      {
        text: filter.constantize.model_name.human(count: ''),
        href: admin_history_items_path(filter: param_filter),
        class: ('active' if params[:filter] == param_filter)
      }
    end << { text: 'Все', href: admin_history_items_path, class: ('active' unless params[:filter]) }

    buttons(filters.reverse)
  end
end

app/views/admin/user_actions/_grid.html.slim
= table_tag
  tbody
    - collection.each do |user_action|
      tr
        td = user_action.author
        td = user_action_change_type_badge_for user_action
        td = "#{user_action.human_changed_object_type} ##{user_action.changed_object_id}"
        td = l user_action.created_at.localtime, format: :long
        td
          - unless user_action.changed_object_is_not_available?
            = show_button user_action

app/views/admin/user_actions/index.html.slim
.card
  .card-header
    .pull-left
      h5 = t('admin.user_actions.grid_header')
    .pull-right
      = collection_filters [t('shared.all'), *resource_class.pluck(:changed_object_type).uniq]
      = export_button url: export_admin_user_actions_path(filter: params[:filter]), size: :sm, class: 'btn-secondary'
  = render 'grid'

app/views/admin/user_actions/show.html.slim
= bootstrap_resource_card
  br

  = table_tag
    thead
      tr
        th Changed Attribute
        th Old Value
        th New Value
    tbody
    - resource.change_set.each_pair do |key, value|
      tr
        td = resource.changed_object.class.human_attribute_name(key)
        td = value.first
        td = value.second

  br

  = cancel_button class: 'btn-block'