config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :common do
    resources :dashboard, only: :index

    resources :media
    resources :schedules
    resources :devices

    root to: 'dashboard#index'
  end

  namespace :admin do
    resources :dashboard, only: :index

    resources :users, only: :edit do
      post :create, on: :collection
    end

    resources :user_actions do
      get :export, on: :collection
    end
  end

  namespace :api do
    resources :devices, only: [] do
      get :schedule, on: :collection
    end
  end

  root to: redirect('/common')
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :bigint           not null, primary key
#  email              :string(255)      default(""), not null
#  encrypted_password :string(255)      default(""), not null
#  admin              :boolean          default(FALSE), not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class User < ApplicationRecord
  include ApplicationContextAccess

  define_context_access :current_user

  devise :database_authenticatable, :validatable

  alias_attribute :is_admin?, :admin

  has_many :devices, class_name: 'Device', dependent: :destroy
  has_many :schedules, class_name: 'Schedule', dependent: :destroy
end

app/models/user_action.rb
# == Schema Information
#
# Table name: user_actions
#
#  id                  :bigint           not null, primary key
#  author              :string(255)      default("N/A"), not null
#  change_type         :string(255)      not null
#  changed_object_type :string(255)
#  changed_object_id   :integer
#  change_set          :text(65535)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class UserAction < ApplicationRecord
  extend EnumerateIt

  belongs_to :changed_object, polymorphic: true, optional: true

  scope :ordered, -> { order('created_at desc') }
  scope :filtered, ->(filter) { select { |item| item.changed_object_type == filter } }

  serialize :change_set, JSON
  has_enumeration_for :change_type, with: ::UserActionType, required: true

  def changed_object_is_not_available?
    changed_object.nil? || change_type == UserActionType::DELETE
  end

  def human_changed_object_type
    changed_object_type.constantize.model_name.human
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  defaults resource_class: User

  def create
    User.create!(
      email: user_params[:email],
      password: user_params[:password],
      password_confirmation: user_params[:password]
    )
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_is_admin?
    current_user&.is_admin?
  end
end

app/views/admin/users/_devices_grid.html.slim
= table_tag
  thead
    tr
      th = resource_class.human_attribute_name(:id)
      th = resource_class.human_attribute_name(:name)
      th = resource_class.human_attribute_name(:status)
      th = t('shared.actions')
  tbody
    - resource.devices.each do |device|
      tr
        td = device.id
        td = device.name
        td = device_status_badge device
        td.inline-btn-toolbar
          = edit_button device, url: edit_common_device_path(device)
          = delete_button device, url: common_device_path(device), method: :delete

app/views/admin/users/_grid.html.slim
= table_tag
  tbody
    - collection.each do |user|
      tr
        td = user.id
        td = user.email
        td.inline-btn-toolbar
          = edit_button user, url: url_for([:edit, :admin, user])

app/views/admin/users/edit.html.slim
.card
  h5.card-header = t('admin.users.devices_grid', username: resource.email)
  = render 'devices_grid'