config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :common do
    resources :dashboard, only: :index

    resources :media
    resources :schedules
    resources :devices

    root to: 'dashboard#index'
  end

  namespace :admin do
    resources :dashboard, only: :index

    resources :users, only: :edit do
      post :create, on: :collection
    end

    resources :user_actions do
      get :export, on: :collection
    end
  end

  namespace :api do
    resources :devices, only: [] do
      get :schedule, on: :collection
    end
  end

  root to: redirect('/common')
end

app/views/layouts/_navbar.html.slim
= navbar_tag
  = navbar_brand

  = navbar_collapse_button

  = navbar_collapse_section
    = navbar_links_set
      = navbar_link 'Media', common_media_index_path, section: :media
      = navbar_link 'Schedules', common_schedules_path, section: :schedules
      = navbar_link 'Devices', common_devices_path, section: :devices

    - if user_is_admin?
      = navbar_links_set position: :right
        = navbar_link 'Admin Panel', admin_dashboard_index_path, section: :admin_dashboard

    - if user_signed_in?
      = navbar_links_set position: :right
        = navbar_authentication_dropdown

app/views/layouts/application.html.slim
doctype html
html
  head
    title = "Camellia #{Rails.env.capitalize}"

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body.container
    = render 'layouts/navbar'
    = yield